FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Copy only the requirements file first to leverage Docker cache
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install gdb
RUN apt-get update && apt-get install -y gdb

# Copy the rest of the application code
COPY . .

# Command to run the backend server
CMD ["python", "main.py"]
